service:
  name: base-db
  simple-settings-controller.enabled: true
  active-sessions-container.enabled: true
  entities-dto-links:
    configurator-caller.enabled: true
    simple-configuration.enabled: true
  simple-worker:
    enabled: true
    wait-on-stop-ms: 8000
    wait-on-restart-ms: 30000
    min-time-per-iteration-ms: 5000
    timeout-runner-life-ms: 45000
  income-topics:
    configurator-caller.enabled: true
    simple-configuration.enabled: true
    standard-loader.enabled: true
    standard-offsets-controller.enabled: true
  outcome-topics:
    configurator-caller.enabled: true
    simple-configuration.enabled: true
    standard-uploader.enabled: true
    standard-offsets-controller.enabled: true
  offsets-loaders:
    jpa.enabled: true
  offsets-savers:
    jpa.enabled: true

# Логирование
logging:
  level:
    org:
      springframework: info
      springframework.orm: info
      springframework.web: info
      hibernate:
        sql: debug
        hql: debug
        type: trace
        type.descriptor: info
        pretty: info
        cache: info
        jdbc: debug

# Настройки Сервера
server:
  port: 7003

#kafka
kafka:
  server: localhost:9092
  income-topics:
    securities: baseSecuritiesRequests
    derivatives: baseDerivativesRequests
  outcome-topics:
    places: basePlaces
    provider-types: baseProviderTypes
    providers: baseProviders
    instrument-types: baseInstrumentTypes
    currencies: baseCurrencies
    securities: baseSecurities
    derivatives: baseDerivatives

#data
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: false
    hibernate:
      ddl-auto: validate # create, create-drop, update, validate
      naming.physical-strategy: ru.gx.data.naming.PhysicalNamingStrategyQuotedImpl
  datasource:
    url: jdbc:postgresql://localhost:5432/gxfin_base
    username: gxfin
    password: 12033021
    # driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
