-- Table: Base.RootObjects

-- DROP TABLE "Base"."RootObjects";

CREATE TABLE IF NOT EXISTS "Base"."RootObjects"
(
    "Id"            int                                                 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Kind_Id"       char            COLLATE pg_catalog."default"        NOT NULL,
    CONSTRAINT "RootObjects_Types_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "RootObjects_fkey_Kind" FOREIGN KEY ("Kind_Id") REFERENCES "Base"."RootObjects_Kinds" ("Id")

) TABLESPACE pg_default;

ALTER TABLE "Base"."RootObjects" OWNER to gxfin;
